root: true
parserOptions:
    sourceType: module
env:
    browser: true
extends: "@puntt/eslint-config"
plugins:
    - "svelte3"
overrides:
    - files: "**/*.svelte"
      processor: "svelte3/svelte3"
    - files: "./server.js"
      parserOptions:
          sourceType: "script"